### ISSUE TITLE
Azure redirect?

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#13]
I started using the project _very_ early on so had a lot of projects using the Azure URL instead of the custom ```buildstats.info``` URL and they all recently stopped working as it looks like the hosting provider has changed.

I've fixed my URLs now, but maybe it would be worth setting up a free Azure instance that 302s to the custom domain?

**Comment by dustinmoris** [comment]
Hi Martin, thanks for letting me know. I wasn't sure if anyone was still using the old Azure URLs and I switched to AWS a while ago since the whole thing runs in a Docker container now and it was a lot cheaper to host in AWS.

I see what you mean with the 302s, but I think I prefer to just let it broken now (if anyone is still affected) and people fix the URLs rather now than never. At least I own buildstats.info and it is easier for me to switch DNS records in the future and can guarantee the availability of it.

**Comment by martincostello** [comment]
No problem! I should have updated to the vanity URL when it was introduced to be honest.

I just thought I'd suggest it.
