### ISSUE TITLE
More Power!

### ISSUE THREAD

**Issue by cleemullins** [dustinmoris/CI-BuildStats#21]
You may need a bit more horse power on your build / badge server. We're pretty consistently seeing timeouts across the board. Would you recommend we run our own server? 

![image](https://user-images.githubusercontent.com/1165321/46305446-4e8d0180-c566-11e8-8336-61a70b53232e.png)

**Comment by dustinmoris** [comment]
Oh wow yeah I just saw in the GKE that I'm hitting the limits of the cheap
box I've got for my cluster. I'll add another VM to the cluster this
evening and see if I can improve a few other things. Unfortunately because
of the nature of the data there's not a whole lot of caching I can do,
because builds and NuGet version constantly change (I already cache for
like 3 minutes).

Let's see how it goes after I scale out.

Thanks for reaching out!

Dustin

**Comment by dustinmoris** [comment]
I have just added a minimum of two VMs to my cluster and also set up an auto scaling policy, so hopefully this will improve the availability. Also looking at my Cloudflare stats I can see there's a much higher usage now than what it was a week ago but also I've seen Cloudflare being able to serve more often a cached version when a build chart or nuget package get served, where it only refreshes every 3 minutes which I think is acceptable.

**Comment by dustinmoris** [comment]
Hi, I think I killed my own service by introducing a severe perf issue where a travis ci project which didn't exist would end up in a loop trying to pull builds forever. I have fixed this issue now. Sorry for the really bad availability the last few days!

**Comment by cleemullins** [comment]
Hah. No problem. 😊

//Chris
