### ISSUE TITLE
Add Support for GitHub Actions

### ISSUE THREAD

**Issue by smorimoto** [dustinmoris/CI-BuildStats#26]
Well, they haven't released a decent API yet... So if they do, I would like to help.

**Comment by sergey-tihon** [comment]
Just for tracking https://github.community/t5/GitHub-Actions/GitHub-Action-build-statistics/td-p/41411

**Comment by imbsky** [comment]
GitHub Actions now have a fresh new API!
https://developer.github.com/v3/actions

**Comment by imbsky** [comment]
@dustinmoris Do you have much time to support this?

**Comment by dustinmoris** [comment]
Hey, I currently don't have much time to work on this but I'd deffinitely accepts PRs!

**Comment by imbsky** [comment]
Sorry, I'm also very busy recently, don't have the bandwidth to do this...

**Comment by imbsky** [comment]
There's still a lot of value in tackling this. Does anyone want to work on it?

**Comment by dustinmoris** [comment]
> There's still a lot of value in tackling this.
Absolutely.

> Does anyone want to work on it?
I might actually have more time this weekend to take a stab at this, but can't make any promises.

**Comment by imbsky** [comment]
Much appreciated, but certainly not demands. Guard your own time carefully 🙂

**Comment by dustinmoris** [comment]
Hello, I've actually got around to get a first version working tonight. For now the GitHub chart can only display a build count up to 30 builds, because that is what the GitHub API returns max per page. When I have more time over the weekend I can extend it so that the GitHub client can query more pages when the `buildCount` parameter is more than 30.

But for now, you can use this version if you wish, works like this:

```
https://buildstats.info/github/chart/dustinmoris/Logfella
```

e.g.:

![GitHub Actions Chart](https://buildstats.info/github/chart/dustinmoris/Logfella)

**Comment by imbsky** [comment]
Insane work!
