### ISSUE TITLE
Travis CI non-master default branch

### ISSUE THREAD

**Issue by davidkassa** [dustinmoris/CI-BuildStats#39]
It seems that my build history stopped working when I changed my default branch from `master` to `main`. Specifying no branch goes to `master`, though I can't tell if it's a history from travis-ci.com or .org. When I specify `main`, no builds are found. I assume this is because it's listed as the default branch.

https://buildstats.info/travisci/chart/davidkassa/dvc-rofr-stats?includeBuildsFromPullRequest=false&branch=main
https://buildstats.info/travisci/chart/davidkassa/dvc-rofr-stats?includeBuildsFromPullRequest=false

**Comment by dustinmoris** [comment]
Hi, sorry about that. Travis did a migration from their .org to their .com environment and it seems that your project was only moved recently. It is impossible to know where a project is currently at with Travis and therefore BuildStats.info tries to query the .com API first and when there are no builds it will query the old .org API. When it finds builds in .org after the fallback then we cache that information for a little while, which is why it kept trying to query from .org for your main branch after the move. I've reset that particular cache and can confirm that the graph works for your main branch now!
