### ISSUE TITLE
Suggestion: Use your own domain

### ISSUE THREAD

**Issue by Daniel15** [dustinmoris/CI-BuildStats#4]
I'd suggest using your own domain rather than the azurewebsites.net subdomain (`ci-buildstats.azurewebsites.net`), even if the domain just redirects to the azurewebsites one. Using an azurewebsites subdomain means all the image URLs will break if you ever move to a different host.

**Comment by dustinmoris** [comment]
Hi Daniel, that is a great suggestion and to be honest I was thinking the same just a few days ago.

The reason why I haven't done this yet is because the widget is running on the free tier at the moment and I will have to move it to a paid tier in order to configure a custom domain. Luckily when I configure the new domain the *.azurewebsites.net URL will remain valid, so I thought there is no rush to get this done.

However, after your suggestion I looked into buying a domain and I might get it setup in the next couple days ;)

Cheers!

**Comment by Daniel15** [comment]
Yeah that's a reason why I suggested getting a domain and just redirecting
from the domain to the azurewebsites subdomain (ie. Continue to use the
subdomain, but only list your custom domain in all the documentation).
It'll give you more flexibility for the future :)

**Comment by dustinmoris** [comment]
I have registered http://buildstats.info/ and all URLs work with this domain now as well.

Example:
http://buildstats.info/appveyor/chart/dustinmoris/ci-buildstats

[![Build history](http://buildstats.info/appveyor/chart/dustinmoris/ci-buildstats)](https://ci.appveyor.com/project/dustinmoris/ci-buildstats/history)

Thank you for this great suggestion!
